Quash TypeError potentially raised by requests -> urllib3
geopy/geopy pull request #488
Opened 2021-08-10 19:01 UTC by tigerhawkvok

Quashes an error raised by requests -> urllib3 -> stdlib:queue -> stdlib:threading where a pool may be done in a thread and therefore no object to close.

Error encountered in both Python 3.7.8 on Windows 10 and 3.7.11 on Debian 10 ( Docker: python3.7-slim). 

Exception ignored in: <function RequestsAdapter.__del__ at 0x7fd2c3fee170>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/geopy/adapters.py", line 431, in __del__
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 747, in close
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 325, in close
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 222, in clear
  File "/usr/local/lib/python3.7/site-packages/urllib3/_collections.py", line 100, in clear
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 173, in <lambda>
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 490, in close
  File "/usr/local/lib/python3.7/queue.py", line 181, in get
  File "/usr/local/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable

2021-08-14 16:27 UTC, KostyaEsmukov approved these changes
Good workaround, thank you!

2021-08-14 16:29 UTC, KostyaEsmukov requested changes
@tigerhawkvok Could you please fix the linting errors?

```
  geopy/adapters.py:434:71: W291 trailing whitespace
  geopy/adapters.py:437:66: W291 trailing whitespace
```

2021-08-16 03:06 UTC, tigerhawkvok reviewed
Trimmed the two lines of whitespace raised by linter

2021-08-16 09:18 UTC, KostyaEsmukov approved these changes

2021-08-16 09:19 UTC, merged

2021-08-16 09:19 UTC, KostyaEsmukov commented
Perfect, thanks again!